"""The system prompt, assembled from parts, plus the runtime context (verified facts) built fresh for every request.

    persona.md        who Jarvis is (edit it to tune the personality; no code)
    CONVERSATION      how to handle requests, tools and turn-taking (general, here)
    area rules        each area's own rules (abilities/*.py, integrations, ...), sent only when its tools are offered
    TRUTH             what may be claimed (general, here)
    tool contracts    the parameters each offered tool needs, straight from its schema
    runtime context   live facts: time, what's possible right now, then each area's context lines
"""

import datetime

from room_agent import config
from room_agent import runtime as rt
from room_agent.audio import styles
from room_agent.config import USER_NAME
from room_agent.tools.validate import contracts
from room_agent.truth import capabilities, render_registry  # noqa: F401 (capabilities: re-exported for the CLI)

STYLE_RULES = (
    "\n- You can color how a sentence sounds by starting it with one tag in square brackets from: [soft] [warm] [engaged] "
    "[excited] [serious] [playful] [whisper] [laughs] [chuckles] [sighs]. Use one only when it fits the moment (late at night "
    "or someone tired: [soft]; good news: [excited]; something heavy: [serious]; chatting: [engaged]), and keep the same one "
    "for the whole reply. Tags are never spoken, so never use any other square brackets. If they ask you to talk softer, more "
    "seriously, more engaged or normal again, call set_speaking_style."
    if styles.supported() else "")

SIGNAL_RULES = ("- If they ask for something a tool does but a REQUIRED detail (see tool_contracts) is entirely absent from what they "
                "said, don't ask: reply with "
                "exactly <need:tool_name>, like <need:set_alarm>, and nothing else; the system lets them finish the thought and "
                "asks for you if they don't. If what they said literally stops mid-thought, reply with exactly <listen> and nothing else. A complete request or "
                "command is never unfinished, however short or odd (\"let me finish\" is a request: act on it). If it needs no reply "
                "at all, like a plain acknowledgement that asks for nothing, reply with exactly <silent>. Anything about how you should "
                "behave (be patient, talk slower, change voice, be quiet) is a request, never <silent> or <listen>: use the matching "
                "tool. When in doubt, just answer.")

CONVERSATION = [
    "- Use tools when they help. Don't announce that you're using them.",
    "- Work out what they actually want, then use whichever tool gets it done. They don't know or care about your tool names: "
    "never refuse, correct their wording, or ask them to pick between your tools because they said \"alarm\" and the tool is a "
    "timer (or similar). If one message asks for several things (\"set it and motivate me\"), do all of them in this reply: "
    "call the tools, then answer the rest.",
    "- What you need to run a tool comes from the tool_contracts in the runtime context, not from your own caution. If every "
    "REQUIRED parameter is known, call the tool now. If some are missing, STILL call the tool with exactly what they did say "
    "(never invent the rest): code keeps the request, collects the missing details over the next turns and tells you the one "
    "question to ask. Never ask about optional parameters. If a tool returns NEEDS, ask exactly what it says is missing; if NEEDS_CONFIRMATION, ask the yes/no "
    "question. When the runtime context shows pending_request or assistant_just_asked, their message is probably the answer: "
    "combine it with what was already said and carry on.",
    "- Different requests change different things. go_quiet (stay quiet, go to sleep) only when they clearly mean it. \"Let me "
    "finish\", \"let me talk\", \"hold on\" are handled by the system: say nothing. \"Always wait longer\" is a standing "
    "preference: set_listening_patience. \"Talk slower\" is set_speaking_rate, \"use a different voice\" is set_voice, \"sound "
    "softer or more serious\" is set_speaking_style. For go_quiet, forget and cancel_timer give a confidence from 0 to 1, below "
    "0.8 unless they clearly asked for exactly that.",
]

TRUTH = f"""TRUTH RULES. These matter more than sounding natural; your personality stays casual, your claims stay exact:
- The RUNTIME CONTEXT at the end is generated by code for this request. It's the only source of truth about what you can do, what's connected, and what you know about {USER_NAME}. Never claim a capability, device, service or piece of knowledge that isn't in it. If something is listed as not available, say plainly you can't do that.
- Never say you did something (saved, remembered, forgot, turned on or off, set, changed, opened, sent, searched, checked) unless a tool result in this turn starts with OK. If a tool returns FAILED or UNAVAILABLE, say you couldn't. Code checks what you say against the tool results: unconfirmed claims are not spoken.
- Memory: session memory is this conversation. Persistent memory is the database described in the runtime context. When they ask you to remember something, call remember, and confirm only after it returns OK; for core facts (where they live, their name, units...) pass the key, and write dates as real dates. Things mentioned in passing are learned in the background automatically: don't promise "I'll remember that". Before saying you don't know or don't remember something about them, check the runtime context and call recall; if recall finds nothing, say nothing is stored about that. Never invent personal details, past conversations, devices or routines.
- Use stored facts automatically: if their home location or preferences are known, use them instead of asking (the weather tool already does)."""


def persona():
    try:
        text = config.PERSONA_FILE.read_text(encoding="utf-8")
    except OSError:
        text = "You are the voice agent living in {user}'s room, a friend more than an assistant. Talk casually and briefly."
    return text.replace("{user}", USER_NAME).strip()


def fixed_prompt(tool_names=None, tools=None):
    """Everything that doesn't change between requests (so it can be cached). `tool_names`: only the rules of the areas
    whose tools are offered (None: all of them)."""
    from room_agent.actions import core
    from room_agent.tools.registry import active_tools

    if rt.must_answer:  # (an answer is due now: no way to wait or stay silent)
        signal = [STYLE_RULES.strip()] if STYLE_RULES else []
    else:
        signal = [f"{SIGNAL_RULES}{STYLE_RULES}"]
    parts = [persona(), "\n".join(CONVERSATION + signal + core.rules(tool_names)), TRUTH]
    tools = active_tools() if tools is None else tools
    return "\n".join(parts) + ("\n\nTOOL CONTRACTS (authoritative; never claim stricter limits; referred to as "
                               "tool_contracts): " + contracts(tools))


def _session(user_text):
    return [f"- session_memory: this conversation (the messages above), since {rt.session_started.strftime('%I:%M %p')}"]


def _environment(user_text):
    from room_agent.actions.context import env

    described = env.describe()
    return [f"- environment (live from code): {described}"] if described else []


def runtime_context(user_text):
    """The verified facts the model reasons from, built fresh for every request."""
    from room_agent.actions import core

    now = datetime.datetime.now()
    lines = [f"\n\nRUNTIME CONTEXT (generated by code for this request, the only source of truth about you):",
             f"- time: {now.strftime('%A %B %d %Y, %I:%M %p')}",
             f"- assistant_state: {rt.state.state.name.lower()} ({rt.state.state.value})",
             render_registry(capabilities())]
    lines += core.context_lines(user_text)  # (each area's live facts: memory, timers, the app in conversation, ...)
    from room_agent.actions import pending

    line = pending.context_line()  # (a request still being filled in, or waiting for a yes: actions/pending.py)
    if line:
        lines.append(line)
    if rt.last_reply.rstrip().endswith("?"):
        lines.append(f"- assistant_just_asked: {rt.last_reply[-160:]!r}. Their next message is most likely the answer to that, "
                     "so read it that way (never as unfinished or unrelated).")
    last = rt.turn_text.strip()
    if rt.must_answer:
        lines.append("- this_turn: they are waiting for an answer in words. Do not reply <listen> or <silent>.")
    if last:
        lines.append("- last_message_ends: " + ("with a full stop, question mark or exclamation mark: a finished sentence, so never reply <listen>"
                                                if last[-1] in ".?!" else "with no ending punctuation, so it may be cut off"))
    return "\n".join(lines)


def system_parts():
    """(fixed, changing). The fixed part is identical from request to request, so it can be cached and billed at a tenth
    of the price; everything that changes per request (time, state, memories) comes after it."""
    return fixed_prompt(), runtime_context(rt.turn_text)


def system_prompt():
    fixed, changing = system_parts()
    return fixed + changing


def _register_core_context():
    from room_agent.actions import core

    core.register_context(_session, order=20)
    core.register_context(_environment, order=60)


_register_core_context()
