"""Tool registry audit: correctness, permissions, likely duplicates, token overhead. Writes TOOL_AUDIT.md.

    .venv\\Scripts\\python -m tests.tool_audit

Offline (no model, no network). The lint rules it applies are also enforced by tests/test_tool_registry.py.
"""

import json
import re

from tests.harness import setup_env

setup_env()

import tiktoken  # noqa: E402

from room_agent.actions import core  # noqa: E402

ENC = tiktoken.get_encoding("o200k_base")
TYPES = {"string", "integer", "number", "boolean", "array", "object"}


def lint(cap):
    """-> [problems] for one capability."""
    out = []
    p = cap.parameters or {}
    props = p.get("properties", {}) or {}
    if p.get("type") != "object":
        out.append("parameters isn't an object schema")
    for r in p.get("required", []):
        if r not in props:
            out.append(f"required '{r}' isn't a property")
    for name, spec in props.items():
        if not isinstance(spec, dict) or spec.get("type") not in TYPES:
            out.append(f"'{name}' has no valid type")
        if "enum" in spec and not spec["enum"]:
            out.append(f"'{name}' has an empty enum")
    if len((cap.description or "").strip()) < 15:
        out.append("description too short")
    for pattern, defaults in cap.reflex or []:
        try:
            rx = re.compile(pattern)
        except re.error as e:
            out.append(f"reflex doesn't compile: {e}")
            continue
        for g in list(rx.groupindex) + list(defaults):
            if g not in props and cap.reflex_check is None:  # (a reflex_check may turn spoken words into arguments)
                out.append(f"reflex fills '{g}', which isn't a parameter")
    if cap.risk in (core.Risk.SENSITIVE, core.Risk.CONFIRM) and cap.describe is None and cap.risk == core.Risk.SENSITIVE:
        out.append("SENSITIVE without describe(): the confirmation question can't say what it will do")
    if cap.risk == core.Risk.CONFIRM and "confidence" not in props and cap.min_confidence:
        out.append("CONFIRM with min_confidence but no 'confidence' parameter")
    return out


def tokens(cap):
    return len(ENC.encode(json.dumps({"name": cap.name, "description": cap.schema()["description"],
                                      "parameters": cap.parameters})))


def duplicates(caps, threshold=0.80):
    """Pairs of tools whose descriptions mean nearly the same (the local meaning model)."""
    try:
        from room_agent.social import meaning

        meaning.ENABLED = True
        meaning.load(wait=True)
        v = meaning.embed([c.description[:300] for c in caps])
    except Exception:
        return []
    sim = v @ v.T
    pairs = []
    for i in range(len(caps)):
        for j in range(i + 1, len(caps)):
            if sim[i, j] >= threshold:
                pairs.append((round(float(sim[i, j]), 2), caps[i].name, caps[j].name))
    return sorted(pairs, reverse=True)


def main():
    core.ensure_loaded()
    caps = core.capabilities()
    rows = [(c, tokens(c), lint(c)) for c in caps]
    total = sum(t for _, t, _ in rows)
    problems = [(c.name, p) for c, _, ps in rows for p in ps]
    dups = duplicates(caps)
    no_claim = [c.name for c in caps if c.changes_state and not c.claim]
    lines = ["# Tool audit", "", f"Generated by `python -m tests.tool_audit` from the live registry: {len(caps)} tools, "
             f"{sum(c.changes_state for c in caps)} change something, {total:,} tokens if every schema were sent at once "
             "(they aren't: only the tools relevant to a request are offered).", "", "## Lint problems", ""]
    lines += [f"- `{n}`: {p}" for n, p in problems] or ["None."]
    lines += ["", "## State-changing tools without a claim kind", "",
              "(Jarvis saying it did one of these isn't cross-checked against the tool's result.)", ""]
    lines += [f"- `{n}`" for n in no_claim] or ["None."]
    lines += ["", "## Likely duplicates (descriptions mean nearly the same)", ""]
    lines += [f"- `{a}` / `{b}` (similarity {s})" for s, a, b in dups] or ["None found."]
    lines += ["", "## Largest schemas (tokens each)", "", "| Tool | Tokens | Group | Risk | Changes | Intent gate | Private |",
              "|---|---|---|---|---|---|---|"]
    for c, tk, _ in sorted(rows, key=lambda r: -r[1])[:25]:
        lines.append(f"| `{c.name}` | {tk} | {c.group or '-'} | {c.risk.value} | {'yes' if c.changes_state else 'no'} | "
                     f"{'yes' if c.intent is not None else 'no'} | {'yes' if c.private else 'no'} |")
    by_group = {}
    for c, tk, _ in rows:
        by_group.setdefault(c.group or "(always)", []).append(tk)
    lines += ["", "## Tokens by area (all tools of the area offered together)", "", "| Area | Tools | Tokens |", "|---|---|---|"]
    lines += [f"| {g} | {len(v)} | {sum(v)} |" for g, v in sorted(by_group.items(), key=lambda kv: -sum(kv[1]))]
    open("TOOL_AUDIT.md", "w", encoding="utf-8").write("\n".join(lines) + "\n")
    print(f"{len(caps)} tools, {total} tokens total, {len(problems)} lint problems, {len(no_claim)} without claim kind, "
          f"{len(dups)} likely duplicate pairs -> TOOL_AUDIT.md")


if __name__ == "__main__":
    main()
